---
# Prerequisites
# https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops
# - Azure Organization
# - Project
# - Personal User Access Token
# - Publisher
#
# - Set Personal Access Token to GitHub Secrets
# - Add dependencies in package.json
# - Create tsconfig.json
# - Create task.json
name: Release
on:
  push:
    tags: [v*]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: get nested property
        id: package_json
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # v0.2.0
        with:
          path: buildandreleasetask/package.json
          prop_path: volta.node
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{steps.package_json.outputs.prop}}

      - run: npm i -g tfx-cli typescript@4.6.3
      - run: npm i
        working-directory: buildandreleasetask

      - run: |
          tfx extension create \
            --manifest-globs vss-extension.json \
            --rev-version
      - run: |
          tfx extension publish \
            -t "${{secrets.AZURE_API_TOKEN}}" \
            --manifest-globs vss-extension.json \
            --share-with ShunsukeSuzuki
